# Configuration file for the parser

seed: 0                     # Random seed for initialization
image_inference: true

# Storage
data_root: '/home/ICT2000/dchang/TAC_project/Face_Heatmap/data'  # Root directory for the data
ckpt_path: './src/AU_Recognition/resnet_disfa_all'  # Path for checkpoint storage

# Data settings
data: 'DISFA'                # Dataset to use
fold: 'all'                  # Data fold to use
num_workers: 0               # Number of workers for data loading
image_size: 256              # Input image size
crop_size: 224               # Cropped image size
num_labels: 12               # Number of labels in the dataset
sigma: 10.0                  # Sigma for heatmap generation

# Model settings
model_name: 'resnet'         # Model architecture to use
dropout: 0.1                 # Dropout rate
hidden_dim: 128              # Hidden dimension for the model
half_precision: false        # Use half precision (FP16)

# Training settings
num_epochs: 30               # Number of epochs to train for
interval: 500                # Interval for some process (e.g., logging, validation)
threshold: 0                 # Threshold value (can be related to model outputs)
batch_size: 256              # Batch size for training
learning_rate: 3e-5          # Learning rate
weight_decay: 1e-4           # Weight decay for optimizer
loss: 'unweighted'           # Loss function type
clip: 1.0                    # Gradient clipping value
when: 10                     # Epoch when to decay the learning rate
patience: 5                  # Patience for early stopping
fm_distillation: false       # Use feature map distillation

# Device settings
device: 'cuda'               # Device to use for computation
