seed: 0
image_inference: true

# Storage
data_root: "/home/ICT2000/dchang/TAC_project/data"
ckpt_path: "./libreface/AU_Detection/fm_distillation_all"

# Data
data: "BP4D"
fold: "all"
num_workers: 0
image_size: 256
crop_size: 224
num_labels: 12
sigma: 10.0

# Model
model_name: "resnet"
dropout: 0.1
hidden_dim: 128
half_precision: false

# Training
num_epochs: 30
interval: 500
threshold: 0.0
batch_size: 256
learning_rate: 3e-5
weight_decay: 1e-4
loss: "unweighted"
clip: 1.0
when: 10
patience: 5
fm_distillation: false

# Device
device: "cuda"
